name: ordermate
description: "A Flutter mobile order booking application."
publish_to: 'none'
version: 1.1.0+8

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.0
  cached_network_image: ^3.3.0
  csv: ^6.0.0
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^10.2.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: 2.3.0
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.0
  go_router: ^14.0.0
  google_fonts: ^6.3.3
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  intl: any
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  logger: ^2.0.0
  lottie: ^3.0.0
  path: ^1.9.1
  path_provider: any
  pinput: ^6.0.1
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^2.3.5
  shimmer: ^3.0.0
  uuid: ^4.0.0
  file_picker: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  image_picker: ^1.0.0

  permission_handler: ^11.3.0
  printing: ^5.14.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+1
  url_launcher: 6.3.0
  connectivity_plus: ^6.0.0
  google_maps_flutter: ^2.6.0
  google_sign_in: ^6.1.0
  image_cropper: ^8.0.0
  pdf: ^3.11.3
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^6.0.0
  supabase_flutter: ^2.5.0
  flutter_local_notifications: ^19.5.0
  http: any
  
  cupertino_icons: ^1.0.0
  app_links: 6.4.1
  mobile_number: ^3.0.0
  mailer: ^6.0.1
  package_info_plus: ^9.0.0
  flutter_localizations:
    sdk: flutter
  local_auth: ^2.2.0
  number_to_character: ^0.0.12
  sqflite_common_ffi_web: ^1.1.1
  screenshot: ^3.0.0
  flutter_email_sender: ^8.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  freezed: ^2.5.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/json/accounting/
    - .env